name: Deploy E-store App to Azure App Service

on:
  push:
    branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Upload JAR to Azure App Services
        uses: actions/upload-artifact@v4
        with:
          name: estore-app-example
          path: ${{ github.workspace }}/target/*.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Azure-App-Service
    steps:
      - name: Download JAR from build job
        uses: actions/download-artifact@v4
        with:
          name: estore-app-example
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: e-store
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: '*.jar'
